### PR TITLE
PR#70 Enable aggressive ticking by default

### PR DESCRIPTION
**Pull request by MilanDierick**
Enable the mod option 'aggressive ticking' by default. Using 'aggressive ticking' seems to solve a lot of desyncing issues.

### CODE REVIEW

**Comment by vasilevp** [comment]
From a players perspective, aggressive ticking can significantly reduce FPS when network conditions are not ideal, even on high-end machines.

**Comment by MilanDierick** [comment]
@vasilevp Enabling aggressive ticking will resolve more issues than it will create, and you need to have a really bad connection in order to get affected by aggressive ticking...

Are you talking about personal experience, or who else do you know of that is unable to use aggressive ticking?

**Review by Parexy — APPROVED** [review]

**Comment by vasilevp** [comment]
@MilanDierick sorry for the late reply...
I'm talking about personal experience, although I haven't tested this in some time now. I wouldn't say it was _impossible_ to play, but the FPS drop was definitely there (100+ to 50-60), so I tried to avoid using this option.
It's probably OK to have this on by default, just needs to be mentioned somewhere as a possible performance hog.

**Comment by MilanDierick** [comment]
@vasilevp Fair enough.

**Comment by SweptWasTaken** [comment]
What's the status on this PR?

**Pull request merged**
