### PR TITLE
Ran Code Cleanup from Rider issue #6

### PR DESCRIPTION
**Pull request by Aivaria**
for issue #6 - Needs review.
Game is running, mod loads, didnt get desync in first tests

### CODE REVIEW

**Comment by Aivaria** [comment]
this shouldnt go directly into master i guess

**Review by tindolt-zz — COMMENTED** [review]
How much testing have you done on this?

**Comment by jacobEAdamson** [comment]
I'm not sure I want to go with the whitespace changes you have here. I tend to prefer spaces over tabs for example, and it looks like you've replaced all spaces with tabs

**Comment by tindolt-zz** [comment]
> I'm not sure I want to go with the whitespace changes you have here. I tend to prefer spaces over tabs for example, and it looks like you've replaced all spaces with tabs

Agreed

**Review by MilanDierick — CHANGES_REQUESTED** [review]
Revert the white space changes

**Comment by Aivaria** [comment]
true, i did replace spaces with tabs - as tabs can be set to a customized size to display 2 or 4 space characters (for example), to fit an developers taste as he needs its.

im gonna change to spaces, gimme a min

**Comment by MilanDierick** [comment]
Could you post a screenshot of the code cleanup settings that you've used? I also included a cleanup profile, but you probably didn't notice. If you do have different settings, could you change the team-wide cleanup profile to reflect your settings? Just to make sure everyone uses the same settings when doing a cleanup. 

Also, make sure you disable the setting "remove redundant code", since it will also remove all the debug statements, which we want to keep.

**Comment by Aivaria** [comment]
you are right, i didnt notice a team profile - where can i find it to fit my settings to?
https://puu.sh/DamNE/acf467e046.png < settings for cleanup, code changes should only have affected tabs > spaces (and otherwise arround)

**Review by MilanDierick — DISMISSED** [review]

**Comment by MilanDierick** [comment]
I just remembered that I reverted my commit yesterday, which included the team profile. Let me try and commit that again, so you can pull that profile.

**Comment by MilanDierick** [comment]
@Aivaria Go ahead and merge [issue#22](https://github.com/Parexy/Multiplayer/tree/issue-22) into your branch, you should be able to select the team profile.

**Comment by Aivaria** [comment]
mind if i force push the new cleanup based on master?

**Comment by SamboyCoding** [comment]
I don't personally have an issue with force-pushing a PR branch, just FPing master.

**Comment by MilanDierick** [comment]
You shouldn't be able to push any commits on the master, you are not a collaborator, and we have protected the master branch. But feel free to commit your latest changes your local branch, and we will review the changes and eventually merge them with the master branch.

**Comment by Aivaria** [comment]
i didnt mean to push to master ;)
i rebased to master, merged #22, and ran the cleanup -- never would i dare to touch the master with those changes :)

**Comment by Aivaria** [comment]
tests i ran:
opened 2 instances of rimworld loading the mod. 1 instance complained about shared use of files.
Loaded a game using the Host menu on Instance 1.
Joined the game on instance 2 using lan (success)
build a few walls (no issue)
placed blueprints (no issue)
let the pawn's attack each other draftet (no issue)

cursor was visible on other client when testing, things happened in sync

**Review by MilanDierick — APPROVED** [review]

**Pull request merged**
